logging:
  file:
    name: lotteOn.log
    path: /logs
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    root: info

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: lotteOn
    version: 1.0

  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    cache: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://52.78.214.92:3306/lotteOn?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Qwerty@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true