server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: lotteOn
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true